"""Assessment, YieldPrediction, IncomeEstimate, Scenario, and Explanation models."""

import uuid
from datetime import date, datetime
from typing import List, Optional
from sqlalchemy import JSON, Date, DateTime, ForeignKey, Index, Numeric, String, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base, CreationTimestampMixin, UUIDPrimaryKeyMixin


class CreditAssessment(Base, UUIDPrimaryKeyMixin, CreationTimestampMixin):
    """Immutable credit assessment snapshot linking agronomic, climate, and credit factors."""

    __tablename__ = "credit_assessments"
    __table_args__ = (
        Index("ix_assessment_tenant_borrower", "institution_id", "borrower_id", "created_at"),
    )

    institution_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("institutions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    borrower_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("borrowers.id", ondelete="CASCADE"), nullable=False, index=True
    )
    loan_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        Uuid, ForeignKey("loans.id", ondelete="SET NULL"), nullable=True, index=True
    )
    model_version_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        Uuid, ForeignKey("model_versions.id", ondelete="SET NULL"), nullable=True
    )
    input_manifest_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, default=uuid.uuid4, nullable=False, doc="Unique snapshot manifest hash/uuid"
    )
    status: Mapped[str] = mapped_column(
        String(50), default="COMPLETED", nullable=False, doc="PENDING, COMPLETED, FAILED"
    )
    result_type: Mapped[str] = mapped_column(
        String(50), default="ASSESSMENT", nullable=False, doc="ASSESSMENT, REASSESSMENT"
    )
    repayment_probability: Mapped[Optional[float]] = mapped_column(
        Numeric(6, 4), nullable=True, doc="Gated: null unless lawful validated credit labels exist"
    )
    pd_status: Mapped[str] = mapped_column(
        String(50), default="NOT_AVAILABLE", nullable=False, doc="NOT_AVAILABLE, CALIBRATED, DEMO_INDICATOR"
    )
    risk_band: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True, doc="LOW, MEDIUM, HIGH, SEVERE"
    )
    dscr: Mapped[Optional[float]] = mapped_column(
        Numeric(8, 4), nullable=True, doc="Debt Service Coverage Ratio (IADS / Debt Service)"
    )
    snapshot_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    trigger_reason: Mapped[str] = mapped_column(
        String(100), default="INITIAL_APPLICATION", nullable=False
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    institution: Mapped["Institution"] = relationship("Institution")
    borrower: Mapped["Borrower"] = relationship("Borrower", back_populates="assessments")
    loan: Mapped[Optional["Loan"]] = relationship("Loan", back_populates="assessments")
    model_version: Mapped[Optional["ModelVersion"]] = relationship("ModelVersion", back_populates="assessments")
    scenarios: Mapped[List["ScenarioRun"]] = relationship(
        "ScenarioRun", back_populates="assessment", cascade="all, delete-orphan"
    )
    explanations: Mapped[List["RiskExplanation"]] = relationship(
        "RiskExplanation", back_populates="assessment", cascade="all, delete-orphan"
    )
    alerts: Mapped[List["Alert"]] = relationship(
        "Alert", back_populates="assessment", cascade="all, delete-orphan"
    )


class YieldPrediction(Base, UUIDPrimaryKeyMixin, CreationTimestampMixin):
    """Crop yield prediction generated by registered model artifact."""

    __tablename__ = "yield_predictions"

    crop_cycle_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("crop_cycles.id", ondelete="CASCADE"), nullable=False, index=True
    )
    model_version_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("model_versions.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    input_manifest_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    value: Mapped[Optional[float]] = mapped_column(Numeric(12, 4), nullable=True)
    unit: Mapped[str] = mapped_column(String(20), default="kg/hectare", nullable=False)
    horizon_start: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    horizon_end: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    quality_status: Mapped[str] = mapped_column(String(50), default="VALID", nullable=False)
    uncertainty_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    limitations_json: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)

    crop_cycle: Mapped["CropCycle"] = relationship("CropCycle", back_populates="yield_predictions")
    model_version: Mapped["ModelVersion"] = relationship("ModelVersion", back_populates="yield_predictions")


class IncomeEstimate(Base, UUIDPrimaryKeyMixin, CreationTimestampMixin):
    """Farm cash flow and debt service capacity estimation."""

    __tablename__ = "income_estimates"

    crop_cycle_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("crop_cycles.id", ondelete="CASCADE"), nullable=False, index=True
    )
    gross_revenue: Mapped[float] = mapped_column(Numeric(16, 2), nullable=False)
    production_costs: Mapped[float] = mapped_column(Numeric(16, 2), nullable=False)
    other_expenses: Mapped[float] = mapped_column(Numeric(16, 2), default=0.0, nullable=False)
    net_farm_income: Mapped[float] = mapped_column(Numeric(16, 2), nullable=False)
    other_household_income: Mapped[float] = mapped_column(Numeric(16, 2), default=0.0, nullable=False)
    debt_service_obligations: Mapped[float] = mapped_column(Numeric(16, 2), default=0.0, nullable=False)
    income_available_for_debt_service: Mapped[float] = mapped_column(Numeric(16, 2), nullable=False)
    currency: Mapped[str] = mapped_column(String(10), default="INR", nullable=False)
    assumptions_version: Mapped[str] = mapped_column(String(50), default="1.0", nullable=False)
    assumptions_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    crop_cycle: Mapped["CropCycle"] = relationship("CropCycle", back_populates="income_estimates")


class ScenarioRun(Base, UUIDPrimaryKeyMixin, CreationTimestampMixin):
    """Perturbation scenario comparison runs (e.g. drought, excessive rainfall)."""

    __tablename__ = "scenario_runs"

    assessment_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("credit_assessments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    scenario_code: Mapped[str] = mapped_column(
        String(100), nullable=False, doc="DROUGHT_MODERATE, DROUGHT_SEVERE, HEAT_STRESS, FLOOD_EXCESS"
    )
    assumptions_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    yield_delta_pct: Mapped[float] = mapped_column(Numeric(8, 4), nullable=False)
    income_delta_pct: Mapped[float] = mapped_column(Numeric(8, 4), nullable=False)
    result_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    evidence_status: Mapped[str] = mapped_column(
        String(50), default="ILLUSTRATIVE_ASSUMPTION", nullable=False, doc="EVIDENCE_BACKED, ILLUSTRATIVE_ASSUMPTION"
    )

    assessment: Mapped["CreditAssessment"] = relationship("CreditAssessment", back_populates="scenarios")


class RiskExplanation(Base, UUIDPrimaryKeyMixin, CreationTimestampMixin):
    """Ranked factor contributions and caveats explaining assessment drivers."""

    __tablename__ = "risk_explanations"

    assessment_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("credit_assessments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    factor_code: Mapped[str] = mapped_column(String(100), nullable=False)
    contribution_value: Mapped[float] = mapped_column(Numeric(10, 4), nullable=False)
    direction: Mapped[str] = mapped_column(String(20), nullable=False, doc="POSITIVE, NEGATIVE, NEUTRAL")
    explanation_type: Mapped[str] = mapped_column(
        String(50), default="MODEL_FEATURE", nullable=False, doc="MODEL_FEATURE, OBSERVED_FACT, SCENARIO_DELTA"
    )
    unit: Mapped[str] = mapped_column(String(50), default="index", nullable=False)
    caveat: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    assessment: Mapped["CreditAssessment"] = relationship("CreditAssessment", back_populates="explanations")


class Alert(Base, UUIDPrimaryKeyMixin, CreationTimestampMixin):
    """Early warning risk alert triggered by environmental or financial thresholds."""

    __tablename__ = "alerts"

    institution_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("institutions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    assessment_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        Uuid, ForeignKey("credit_assessments.id", ondelete="SET NULL"), nullable=True, index=True
    )
    rule_code: Mapped[str] = mapped_column(String(100), nullable=False)
    severity: Mapped[str] = mapped_column(String(50), default="WARNING", nullable=False)
    message: Mapped[str] = mapped_column(String(500), nullable=False)
    status: Mapped[str] = mapped_column(String(50), default="ACTIVE", nullable=False)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    assessment: Mapped[Optional["CreditAssessment"]] = relationship("CreditAssessment", back_populates="alerts")
