"""Add borrower auth fields

Revision ID: cd0863cb101b
Revises: f54aad94240a
Create Date: 2026-10-10 01:58:30.799055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0863cb101b'
down_revision: Union[str, None] = 'f54aad94240a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('borrowers', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('borrowers', sa.Column('phone_verified', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_borrowers_contact_phone'), 'borrowers', ['contact_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrowers_contact_phone'), table_name='borrowers')
    op.drop_column('borrowers', 'phone_verified')
    op.drop_column('borrowers', 'hashed_password')
    # ### end Alembic commands ###
