"""initial_schema

Revision ID: f54aad94240a
Revises: 
Create Date: 2026-10-09 12:00:40.439124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54aad94240a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('terms_uri', sa.String(length=255), nullable=True),
    sa.Column('license_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_table('institutions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=True)
    op.create_table('market_prices',
    sa.Column('commodity_code', sa.String(length=50), nullable=False),
    sa.Column('variety_grade', sa.String(length=100), nullable=True),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('price_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_commodity_code'), 'market_prices', ['commodity_code'], unique=False)
    op.create_index(op.f('ix_market_prices_market_id'), 'market_prices', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_prices_observed_at'), 'market_prices', ['observed_at'], unique=False)
    op.create_index('ix_market_prices_query', 'market_prices', ['commodity_code', 'market_id', 'observed_at'], unique=False)
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('artifact_uri', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=50), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_index(op.f('ix_model_versions_name'), 'model_versions', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('branches',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_institution_branch_code')
    )
    op.create_index(op.f('ix_branches_institution_id'), 'branches', ['institution_id'], unique=False)
    op.create_table('jobs',
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_idempotency', 'jobs', ['institution_id', 'idempotency_key'], unique=True)
    op.create_index(op.f('ix_jobs_institution_id'), 'jobs', ['institution_id'], unique=False)
    op.create_index('ix_jobs_status_available', 'jobs', ['status', 'available_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('source_records',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('raw_uri', sa.String(length=500), nullable=True),
    sa.Column('transform_version', sa.String(length=50), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_index('ix_source_records_tracking', 'source_records', ['source_id', 'external_id', 'transform_version'], unique=False)
    op.create_table('users',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_subject'), 'users', ['external_subject'], unique=True)
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_institution_id'), 'audit_events', ['institution_id'], unique=False)
    op.create_index('ix_audit_events_object', 'audit_events', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_audit_events_tenant_time', 'audit_events', ['institution_id', 'timestamp'], unique=False)
    op.create_table('borrowers',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('external_ref', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowers_branch_id'), 'borrowers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_borrowers_institution_id'), 'borrowers', ['institution_id'], unique=False)
    op.create_index('ix_borrowers_tenant_external_ref', 'borrowers', ['institution_id', 'external_ref'], unique=True)
    op.create_table('user_branches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'branch_id', name='uq_user_branch')
    )
    op.create_index(op.f('ix_user_branches_branch_id'), 'user_branches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_branches_user_id'), 'user_branches', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('farms',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('borrower_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('area_unit', sa.String(length=20), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_borrower_id'), 'farms', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_farms_institution_id'), 'farms', ['institution_id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('borrower_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_borrower_id'), 'loan_applications', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_branch_id'), 'loan_applications', ['branch_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_institution_id'), 'loan_applications', ['institution_id'], unique=False)
    op.create_table('loans',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('borrower_id', sa.Uuid(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_loans_borrower_id'), 'loans', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_loans_institution_id'), 'loans', ['institution_id'], unique=False)
    op.create_table('plots',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('area_unit', sa.String(length=20), nullable=False),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plots_farm_id'), 'plots', ['farm_id'], unique=False)
    op.create_table('climate_observations',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('variable_code', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spatial_reference', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_climate_obs_plot_var_time', 'climate_observations', ['plot_id', 'variable_code', 'observed_at'], unique=False)
    op.create_index(op.f('ix_climate_observations_observed_at'), 'climate_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_climate_observations_plot_id'), 'climate_observations', ['plot_id'], unique=False)
    op.create_table('credit_assessments',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('borrower_id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=True),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('input_manifest_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('repayment_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pd_status', sa.String(length=50), nullable=False),
    sa.Column('risk_band', sa.String(length=50), nullable=True),
    sa.Column('dscr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_tenant_borrower', 'credit_assessments', ['institution_id', 'borrower_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_credit_assessments_borrower_id'), 'credit_assessments', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_credit_assessments_institution_id'), 'credit_assessments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_credit_assessments_loan_id'), 'credit_assessments', ['loan_id'], unique=False)
    op.create_table('crop_cycles',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('crop_code', sa.String(length=50), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=False),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('area_unit', sa.String(length=20), nullable=False),
    sa.Column('irrigation_type', sa.String(length=50), nullable=False),
    sa.Column('irrigation_reliability', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycles_crop_code'), 'crop_cycles', ['crop_code'], unique=False)
    op.create_index(op.f('ix_crop_cycles_plot_id'), 'crop_cycles', ['plot_id'], unique=False)
    op.create_index(op.f('ix_crop_cycles_season'), 'crop_cycles', ['season'], unique=False)
    op.create_table('forecasts',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('variable_code', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_model', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_plot_valid_time', 'forecasts', ['plot_id', 'variable_code', 'valid_time'], unique=False)
    op.create_index(op.f('ix_forecasts_plot_id'), 'forecasts', ['plot_id'], unique=False)
    op.create_index(op.f('ix_forecasts_valid_time'), 'forecasts', ['valid_time'], unique=False)
    op.create_table('repayment_schedules',
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('interest_component', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repayment_schedule_loan_ver', 'repayment_schedules', ['loan_id', 'version', 'due_date'], unique=False)
    op.create_index(op.f('ix_repayment_schedules_loan_id'), 'repayment_schedules', ['loan_id'], unique=False)
    op.create_table('satellite_observations',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('vegetation_index', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cloud_fraction', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_version', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sat_obs_plot_acquired', 'satellite_observations', ['plot_id', 'product_code', 'acquired_at'], unique=False)
    op.create_index(op.f('ix_satellite_observations_acquired_at'), 'satellite_observations', ['acquired_at'], unique=False)
    op.create_index(op.f('ix_satellite_observations_plot_id'), 'satellite_observations', ['plot_id'], unique=False)
    op.create_table('soil_moisture',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('depth_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spatial_resolution', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_moisture_observed_at'), 'soil_moisture', ['observed_at'], unique=False)
    op.create_index(op.f('ix_soil_moisture_plot_id'), 'soil_moisture', ['plot_id'], unique=False)
    op.create_index('ix_soil_moisture_plot_observed', 'soil_moisture', ['plot_id', 'observed_at'], unique=False)
    op.create_table('alerts',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['credit_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_assessment_id'), 'alerts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_alerts_institution_id'), 'alerts', ['institution_id'], unique=False)
    op.create_table('income_estimates',
    sa.Column('crop_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('production_costs', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('other_expenses', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_farm_income', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('other_household_income', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('debt_service_obligations', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('income_available_for_debt_service', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('assumptions_version', sa.String(length=50), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_estimates_crop_cycle_id'), 'income_estimates', ['crop_cycle_id'], unique=False)
    op.create_table('repayment_events',
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('days_past_due', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayment_events_loan_id'), 'repayment_events', ['loan_id'], unique=False)
    op.create_index(op.f('ix_repayment_events_paid_at'), 'repayment_events', ['paid_at'], unique=False)
    op.create_table('risk_explanations',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('factor_code', sa.String(length=100), nullable=False),
    sa.Column('contribution_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('explanation_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('caveat', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['credit_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_explanations_assessment_id'), 'risk_explanations', ['assessment_id'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_code', sa.String(length=100), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('yield_delta_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('income_delta_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['credit_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_runs_assessment_id'), 'scenario_runs', ['assessment_id'], unique=False)
    op.create_table('yield_predictions',
    sa.Column('crop_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('input_manifest_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('horizon_start', sa.Date(), nullable=True),
    sa.Column('horizon_end', sa.Date(), nullable=True),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('uncertainty_json', sa.JSON(), nullable=True),
    sa.Column('limitations_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yield_predictions_crop_cycle_id'), 'yield_predictions', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_yield_predictions_model_version_id'), 'yield_predictions', ['model_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yield_predictions_model_version_id'), table_name='yield_predictions')
    op.drop_index(op.f('ix_yield_predictions_crop_cycle_id'), table_name='yield_predictions')
    op.drop_table('yield_predictions')
    op.drop_index(op.f('ix_scenario_runs_assessment_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_risk_explanations_assessment_id'), table_name='risk_explanations')
    op.drop_table('risk_explanations')
    op.drop_index(op.f('ix_repayment_events_paid_at'), table_name='repayment_events')
    op.drop_index(op.f('ix_repayment_events_loan_id'), table_name='repayment_events')
    op.drop_table('repayment_events')
    op.drop_index(op.f('ix_income_estimates_crop_cycle_id'), table_name='income_estimates')
    op.drop_table('income_estimates')
    op.drop_index(op.f('ix_alerts_institution_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assessment_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_soil_moisture_plot_observed', table_name='soil_moisture')
    op.drop_index(op.f('ix_soil_moisture_plot_id'), table_name='soil_moisture')
    op.drop_index(op.f('ix_soil_moisture_observed_at'), table_name='soil_moisture')
    op.drop_table('soil_moisture')
    op.drop_index(op.f('ix_satellite_observations_plot_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_acquired_at'), table_name='satellite_observations')
    op.drop_index('ix_sat_obs_plot_acquired', table_name='satellite_observations')
    op.drop_table('satellite_observations')
    op.drop_index(op.f('ix_repayment_schedules_loan_id'), table_name='repayment_schedules')
    op.drop_index('ix_repayment_schedule_loan_ver', table_name='repayment_schedules')
    op.drop_table('repayment_schedules')
    op.drop_index(op.f('ix_forecasts_valid_time'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_plot_id'), table_name='forecasts')
    op.drop_index('ix_forecast_plot_valid_time', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_crop_cycles_season'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_plot_id'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_crop_code'), table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index(op.f('ix_credit_assessments_loan_id'), table_name='credit_assessments')
    op.drop_index(op.f('ix_credit_assessments_institution_id'), table_name='credit_assessments')
    op.drop_index(op.f('ix_credit_assessments_borrower_id'), table_name='credit_assessments')
    op.drop_index('ix_assessment_tenant_borrower', table_name='credit_assessments')
    op.drop_table('credit_assessments')
    op.drop_index(op.f('ix_climate_observations_plot_id'), table_name='climate_observations')
    op.drop_index(op.f('ix_climate_observations_observed_at'), table_name='climate_observations')
    op.drop_index('ix_climate_obs_plot_var_time', table_name='climate_observations')
    op.drop_table('climate_observations')
    op.drop_index(op.f('ix_plots_farm_id'), table_name='plots')
    op.drop_table('plots')
    op.drop_index(op.f('ix_loans_institution_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_loan_applications_institution_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_branch_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_borrower_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_farms_institution_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_borrower_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_branches_user_id'), table_name='user_branches')
    op.drop_index(op.f('ix_user_branches_branch_id'), table_name='user_branches')
    op.drop_table('user_branches')
    op.drop_index('ix_borrowers_tenant_external_ref', table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_institution_id'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_branch_id'), table_name='borrowers')
    op.drop_table('borrowers')
    op.drop_index('ix_audit_events_tenant_time', table_name='audit_events')
    op.drop_index('ix_audit_events_object', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_institution_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_subject'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_source_records_tracking', table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_table('role_permissions')
    op.drop_index('ix_jobs_status_available', table_name='jobs')
    op.drop_index(op.f('ix_jobs_institution_id'), table_name='jobs')
    op.drop_index('ix_jobs_idempotency', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_branches_institution_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_model_versions_name'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('ix_market_prices_query', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_observed_at'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_market_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_commodity_code'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
